/* Created with SQL Script Builder v.2.1.0.28 */
/* From source : plantomatic  */
/* Type of SQL : MS SQL */



CREATE TABLE [item] (
[ItemID] [int] IDENTITY (1,1) NOT NULL,
[ShipmentID] [int] NOT NULL,
[PlantID] [int] NOT NULL,
[DateAvailable] [datetime] NOT NULL,
[Quantity] [int] NOT NULL,
[Size] [varchar] (50),
PRIMARY KEY([ItemID])
)
GO

SET IDENTITY_INSERT [item] ON
INSERT INTO [item] ([ItemID],[ShipmentID],[PlantID],[DateAvailable],[Quantity],[Size])
 VALUES ('1','1','11','10/13/2009 5:04:12 PM','100','1 Gal')
SET IDENTITY_INSERT [item] OFF
 
CREATE TABLE [plant] (
[PlantID] [int] IDENTITY (1,1) NOT NULL,
[Symbol] [varchar] (20) NOT NULL,
[SynonymSymbol] [varchar] (20),
[ScientificNameWithAuthor] [varchar] (250) NOT NULL,
[CommonName] [varchar] (150),
[Family] [varchar] (150),
PRIMARY KEY([PlantID])
)
GO
SET IDENTITY_INSERT [plant] ON
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11','ABIES',NULL,'Abies Mill.','fir','Pinaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('512','ACSH',NULL,'Acamptopappus shockleyi A. Gray','Shockley''s goldenhead','Asteraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('546','ACARO2',NULL,'Acarospora A. Massal.','cracked lichen','Acarosporaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('771','ACSAS',NULL,'Acer saccharum Marsh. var. saccharum','sugar maple','Aceraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('882','ACHLY',NULL,'Achlys DC.','achlys','Berberidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1024','ACSPS',NULL,'Achyranthes splendens Mart. ex Moq. var. splendens','Maui chaff flower','Amaranthaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1026','ACHYR3',NULL,'Achyronychia Torr. & A. Gray','achyronychia','Caryophyllaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1028','ACICA',NULL,'Acicarpha Juss.','acicarpha','Calyceraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1030','ACIDA',NULL,'Acidanthera Hochst.','acidanthera','Iridaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1039','ACISA',NULL,'Acisanthera P. Br.','acisanthera','Melastomataceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1042','ACLEI',NULL,'Acleisanthes A. Gray','trumpets','Nyctaginaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1116','ACORU',NULL,'Acorus L.','sweetflag','Acoraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1163','ACROP2',NULL,'Acroporium Mitt.','acroporium moss','Sematophyllaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1210','ACTIN3',NULL,'Actinidia Lindl.','actinidia','Actinidiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1214','ACTIN',NULL,'Actinostachys Wall.','actinostachys','Schizaeaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1351','ADOXA',NULL,'Adoxa L.','adoxa','Adoxaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1444','AESCU',NULL,'Aesculus L.','buckeye','Hippocastanaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('1694','AGATH2',NULL,'Agathis Salisb.','agathis','Araucariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('2097','AGYRI',NULL,'Agyrium Fr.','agyrium lichen','Agyriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('2111','AILAN',NULL,'Ailanthus Desf.','ailanthus','Simaroubaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('2142','AKEBI',NULL,'Akebia Decne.','chocolate vine','Lardizabalaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('2204','ALECT3',NULL,'Alectoria Ach.','witch''s hair lichen','Alectoriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('2314','ALISM',NULL,'Alisma L.','water plantain','Alismataceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('2560','ALOD2',NULL,'Allium odorum L.','Chinese chives','Liliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('2785','ALOE',NULL,'Aloe L.','aloe','Aloaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('2900','ALSOP',NULL,'Alsophila R. Br.','alsophila','Cyatheaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3165','AMBLY3',NULL,'Amblyodon P. Beauv.','amblyodon moss','Meesiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3329','AMUTU',NULL,'Amelanchier utahensis Koehne var. utahensis','Utah serviceberry','Rosaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3348','AMMAN',NULL,'Ammannia L.','redstem','Lythraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3387','AMORE',NULL,'Amoreuxia Moc. & Sess&#8730;© ex DC.','yellowshow','Bixaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3584','AMTH',NULL,'Amsonia tharpii Woodson','feltleaf bluestar','Apocynaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3591','AMYGD2',NULL,'Amygdalaria Norman','amygdalaria lichen','Porpidiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3606','AMYRI',NULL,'Amyris P. Br.','torchwood','Rutaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3612','ANACA2',NULL,'Anacamptodon Brid.','anacamptodon moss','Fabroniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3616','ANACA',NULL,'Anacardium L.','anacardium','Anacardiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3706','ANDRE2',NULL,'Andreaea Hedw.','andreaea moss','Andreaeaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3745','ANDRE3',NULL,'Andreaeobryum Steere & B.M. Murray','andreaeobryum moss','Andreaeobryaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3843','ANSEG2',NULL,'Androsace septentrionalis L. ssp. glandulosa (Woot. & Standl.) G.T. Robbins','pygmyflower rockjasmine','Primulaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3863','ANEIL2',NULL,'Aneilema R. Br.','aneilema','Commelinaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3869','ANEMA',NULL,'Anema Nyl. ex Forss.','anema lichen','Lichinaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('3871','ANEMI',NULL,'Anemia Sw.','anemia fern','Anemiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('4099','ANDI9',NULL,'Anisomeridium distans (Willey) R.C. Harris','anisomeridium lichen','Monoblastiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('4180','ANOMO',NULL,'Anomodon Hook. & Taylor','anomodon moss','Anomodontaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('4608','ANSC13',NULL,'Anthoceros scariosus Austin','hornwort','Anthocerotaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('4634','ANTHR2',NULL,'Anthracothecium Hampe ex A. Massal.','anthracothecium lichen','Pyrenulaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('4673','ANTID2',NULL,'Antidaphne Poepp. & Endl.','antidaphne','Eremolepidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('4826','APLOD2',NULL,'Aplodon R. Br.','aplodon moss','Splachnaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('4873','APONO',NULL,'Aponogeton L. f.','aponogeton','Aponogetonaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('4880','APTER',NULL,'Apteria Nutt.','apteria','Burmanniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('5120','ARLED',NULL,'Arabis lemmonii S. Watson var. depauperata (A. Nelson & Kennedy) Rollins','soldier rockcress','Brassicaceae')
GO
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('5377','ARVA',NULL,'Arceuthobium vaginatum (Willd.) J. Presl','pineland dwarf mistletoe','Viscaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('5378','ARCHI6',NULL,'Archidium Brid.','archidium moss','Archidiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('5435','ARCTO7',NULL,'Arctomia Th. Fr.','arctomia lichen','Arctomiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('5632','ARRE7',NULL,'Arctostaphylos regismontana Eastw.','Kings Mountain manzanita','Ericaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('5888','ARMUR2',NULL,'Argemone munita Durand & Hilg. ssp. robusta G.B. Ownbey','flatbud pricklypoppy','Papaveraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('6197','ARIST2',NULL,'Aristolochia L.','dutchman''s pipe','Aristolochiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('6763','ARTHO',NULL,'Arthonia Ach.','dot lichen','Arthoniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('6913','ARTE12',NULL,'Arthopyrenia texensis (Cooke) D. Hawksw.','Texas shell lichen','Arthopyreniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('6914','ARTHO3',NULL,'Arthothelium A. Massal.','arthothelium lichen','Uncertain Lichen Family')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('6945','ARTHR5',NULL,'Arthrorhaphis Th. Fr.','arthrorhaphis lichen','Arthrorhaphidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('7168','ASSP2',NULL,'Asclepias sperryi Woodson','Sperry''s milkweed','Asclepiadaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('7263','ASPIC2',NULL,'Aspicilia A. Massal.','rimmed lichen','Hymeneliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('7426','ASER9',NULL,'Asplenium erosum L.','eared spleenwort','Aspleniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('8448','ASPUC',NULL,'Astragalus purshii Douglas ex Hook. var. concinnus Barneby','woollypod milkvetch','Fabaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('8705','ASSIM2',NULL,'Astrolepis sinuata (Lag. ex Sw.) Benham & Windham ssp. mexicana Benham','Mexican scaly cloakfern','Pteridaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('8720','ASTRO3',NULL,'Astrothelium Eschw.','astrothelium lichen','Trypetheliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('8737','ATAMI',NULL,'Atamisquea Miers ex Hook. & Arn.','atamisquea','Capparaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('8745','ATHEL',NULL,'Athelia Pers.','athelia lichen','Atheliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('8960','ATLO3',NULL,'Atriplex longitrichoma Stutz, G.L. Chu & S.C. Sand.','long-hair silverscale','Chenopodiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9068','AULAC2',NULL,'Aulacomnium Schw&#8730;§gr.','aulacomnium moss','Aulacomniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9216','AVBI',NULL,'Averrhoa bilimbi L.','bilimbi','Oxalidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9218','AVICE',NULL,'Avicennia L.','mangrove','Verbenaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9256','AZADI2',NULL,'Azadirachta A. Juss.','azadirachta','Meliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9260','AZOLL',NULL,'Azolla Lam.','mosquitofern','Azollaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9306','BACID',NULL,'Bacidia De Not.','dotted lichen','Bacidiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9475','BAILL',NULL,'Baillonella Pierre','baillonella','Sapotaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9477','BALAN',NULL,'Balanites Delile','balanites','Zygophyllaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9662','BARBE',NULL,'Barbella Fleisch.','barbella moss','Meteoriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9743','BARTR2',NULL,'Bartramia Hedw.','bartramia moss','Bartramiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9771','BASEL',NULL,'Basella L.','basella','Basellaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('9826','BATIS',NULL,'Batis P. Br.','turtleweed','Bataceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('10196','BIATO3',NULL,'Biatorella De Not.','biatorella lichen','Biatorellaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('10496','BLTR',NULL,'Blepharoneuron tricholepis (Torr.) Nash','pine dropseed','Poaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('10520','BLIND2',NULL,'Blindia Bruch & Schimp.','blindia moss','Seligeriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('10682','BONTI',NULL,'Bontia L.','bontia','Myoporaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11008','BRSY2',NULL,'Brachymenium systylium (M&#8730;ºll. Hal.) A. Jaeger','brachymenium moss','Bryaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11029','BRACH10',NULL,'Brachythecium Schimp.','brachythecium moss','Brachytheciaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11400','BRIGA',NULL,'Brigantiaea Trevis.','brigantiaea lichen','Brigantiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11755','BRUCH',NULL,'Bruchia Schw&#8730;§gr.','bruchia moss','Bruchiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11777','BRSU3',NULL,'Brugmansia suaveolens (Humb. & Bonpl. ex Willd.) Bercht. & C. Presl','angel''s-tears','Solanaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11780','BRUGU',NULL,'Bruguiera Savigny','bruguiera','Rhizophoraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11786','BRUNE',NULL,'Brunellia Ruiz & Pav.','brunellia','Brunelliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11823','BRYOB',NULL,'Bryobrittonia R.S. Williams','bryobrittonia moss','Encalyptaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('11946','BRYOX',NULL,'Bryoxiphium Mitt.','bryoxiphium moss','Bryoxiphiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12106','BUDDL2',NULL,'Buddleja L.','butterflybush','Buddlejaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12293','BULLA',NULL,'Bullatina Vezda & Poelt','bullatina lichen','Gomphillaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12299','BUNCH',NULL,'Bunchosia Rich. ex Kunth','woodland coffee','Malpighiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12344','BUTOM',NULL,'Butomus L.','butomus','Butomaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12348','BUXBA2',NULL,'Buxbaumia Hedw.','buxbaumia moss','Buxbaumiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12355','BUXUS',NULL,'Buxus L.','boxwood','Buxaceae')
GO
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12388','CABOM',NULL,'Cabomba Aubl.','fanwort','Cabombaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12665','CALAT',NULL,'Calathea G. Mey.','calathea','Marantaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12685','CALIC',NULL,'Calicium Pers.','spike lichen','Caliciaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('12879','CALLI6',NULL,'Callitriche L.','water-starwort','Callitrichaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('13056','CALOP',NULL,'Calophyllum L.','calophyllum','Clusiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('13063','CALOP7',NULL,'Caloplaca Th. Fr.','orange lichen','Teloschistaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('13350','CALYC5',NULL,'Calycanthus L.','sweetshrub','Calycanthaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('13439','CALYM',NULL,'Calymperes Sw.','calymperes moss','Calymperaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('13569','CAPUP2',NULL,'Calystegia purpurata (Greene) Brummitt ssp. purpurata','Pacific false bindweed','Convolvulaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('14080','CAATC3',NULL,'Campylopus atrovirens De Not. var. cucullatifolius J.-P. Frahm','campylopus moss','Dicranaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('14106','CAMPY5',NULL,'Campylostelium Bruch & Schimp.','campylostelium moss','Ptychomitriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('14120','CANAR2',NULL,'Canarium L.','olive','Burseraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('14167','CANDE2',NULL,'Candelaria A. Massal.','lemon lichen','Candelariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('14206','CANEL',NULL,'Canella P. Br.','wild cinnamon','Canellaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('14210','CANNA2',NULL,'Canna L.','canna','Cannaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('14592','CAAM10',NULL,'Carex amplifolia Boott','bigleaf sedge','Cyperaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('15829','CARLU',NULL,'Carludovica Ruiz & Pav.','carludovica','Cyclanthaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('15872','CAED3',NULL,'Carpobrotus edulis (L.) L. Bolus','hottentot fig','Aizoaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('15963','CARYO2',NULL,'Caryocar F. Allam. ex L.','caryocar','Caryocaraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('16128','CAAPP4',NULL,'Castilleja applegatei Fernald ssp. pinetorum (Fernald) T.I. Chuang & Heckard','wavyleaf Indian paintbrush','Scrophulariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('16387','CASUA',NULL,'Casuarina Rumph. ex L.','sheoak','Casuarinaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('16416','CATAP2',NULL,'Catapyrenium Flotow','earth lichen','Verrucariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('16508','CATOL',NULL,'Catolechia Flotow','catolechia lichen','Rhizocarpaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('16520','CATOS2',NULL,'Catoscopium Brid.','golf club moss','Catoscopiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('16572','CAULE',NULL,'Caulerpa J.V.F. Lamouroux','caulerpa','Caulerpaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('16744','CECRO',NULL,'Cecropia Loefl.','pumpwood','Cecropiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('16783','CELTI',NULL,'Celtis L.','hackberry','Ulmaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('16977','CENTR',NULL,'Centranthus Neck. ex Lam. & DC.','centranthus','Valerianaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('17041','CEPHA4',NULL,'Cephalaria Schrad. ex Roem. & Schult.','cephalaria','Dipsacaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('17049','CEPHA8',NULL,'Cephalotaxus Siebold & Zucc. ex Endl.','cephalotaxus','Cephalotaxaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('17285','CERAT',NULL,'Ceratophyllum L.','hornwort','Ceratophyllaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('17302','CERAT2',NULL,'Ceratopteris Brongn.','antlerfern','Parkeriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('17318','CERCI3',NULL,'Cercidiphyllum Siebold & Zucc.','katsura tree','Cercidiphyllaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('17408','CEAR7',NULL,'Cetraria arenaria Karnefelt','sandwort cetraria lichen','Parmeliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('17550','CHAEN5',NULL,'Chaenothecopsis Vain.','chaenothecopsis lichen','Mycocaliciaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('17920','CHCES',NULL,'Chamaesyce celastroides (Boiss.) Croizat & O. Deg. var. stokesii (Forbes) O. Deg. & I. Deg.','ekoko','Euphorbiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('18636','CHIMA',NULL,'Chimaphila Pursh','prince''s pine','Pyrolaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('18692','CHIRA',NULL,'Chiranthodendron Cerv. ex Cav.','chiranthodendron','Sterculiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('18954','CHRYS15',NULL,'Chrysolepis Hjelmquist','chinquapin','Fagaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('19118','CHRYS12',NULL,'Chrysothrix Mont.','dust lichen','Chrysotrichaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('19200','CIEL2',NULL,'Cinnamomum elongatum (Vahl ex Nees) Kosterm.','laurel avispillo','Lauraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('19536','CISSU',NULL,'Cissus L.','treebine','Vitaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('19714','CLSA6',NULL,'Cladina sandstedei (Abbayes) Ahti','Sandstede''s reindeer lichen','Cladoniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('19968','CLPO8',NULL,'Clappertonia polyandra (K. Schum. ex Sprague) Bech.','clappertonia','Tiliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('20092','CLATH',NULL,'Clathroporina M&#8730;ºll. Arg.','clathroporina lichen','Trichotheliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('20480','CLCLR',NULL,'Clermontia clermontioides (Gaudich.) A. Heller ssp. rockiana (E. Wimm.) Lammers','Kauai clermontia','Campanulaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('20581','CLETH',NULL,'Clethra L.','sweetpepperbush','Clethraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('20609','CLIMA2',NULL,'Climacium F. Weber & D. Mohr ex Mohr','climacium moss','Climaciaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('20709','CLYPE',NULL,'Clypeococcum D. Hawksw.','clypeococcum lichen','Dacampiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('20748','COCCO4',NULL,'Coccocarpia Pers.','coccocarpia lichen','Coccocarpiaceae')
GO
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('20793','COCCO5',NULL,'Coccotrema M&#8730;ºll. Arg.','coccotrema lichen','Coccotremataceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('20992','COUNG',NULL,'Collema undulatum Laurer ex Flotow var. granulosum Degel.','undulate jelly lichen','Collemataceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('21230','COMPT',NULL,'Comptonia L''H&#8730;©r. ex Aiton','sweet fern','Myricaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('21248','COHOE',NULL,'Condalia hookeri M.C. Johnst. var. edwardsiana (Cory) M.C. Johnst.','Edwards'' bluewood','Rhamnaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('21266','CONIM',NULL,'Conimitella Rydb.','conimitella','Saxifragaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('21268','CONIO3',NULL,'Coniocybe Ach.','pin lichen','Coniocybaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('21285','CONOC',NULL,'Conocarpus L.','mangrove','Combretaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('21297','CONOP',NULL,'Conopholis Wallr.','cancer-root','Orobanchaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('21312','CONOT',NULL,'Conotrema Tuck.','conotrema lichen','Stictidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('21839','CORNU',NULL,'Cornus L.','dogwood','Cornaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('22016','COMIT2',NULL,'Corydalis micrantha (Engelm. ex A. Gray) A. Gray ssp. texensis G.B. Ownbey','Texan fumewort','Fumariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('22027','CORYL2',NULL,'Corylopsis Siebold & Zucc.','winter hazel','Hamamelidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('22029','CORYL',NULL,'Corylus L.','hazelnut','Betulaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('22087','CORYN2',NULL,'Corynocarpus J.R. Forst. & G. Forst.','corynocarpus','Corynocarpaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('22140','COSTU',NULL,'Costus L.','costus','Costaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('22300','CRANI2',NULL,'Craniolaria L.','craniolaria','Pedaliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('23189','CROCY',NULL,'Crocynia (Ach.) A. Massal.','crocynia lichen','Crocyniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('23192','CROOM',NULL,'Croomia Torr.','croomia','Stemonaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('23456','CRYPH',NULL,'Cryphaea F. Weber','cryphaea moss','Cryphaeaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('23553','CRDE',NULL,'Cryptantha decipiens (M.E. Jones) A. Heller','gravelbar cryptantha','Boraginaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('23808','CUFI',NULL,'Cucumis ficifolius A. Rich.','cucumis','Cucurbitaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('24064','CUWA2',NULL,'Cuscuta warneri Yunck.','Warner''s dodder','Cuscutaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('24322','CYBIA',NULL,'Cybianthus Mart.','cybianthus','Myrsinaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('24325','CYCAS',NULL,'Cycas L.','cycad','Cycadaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('24349','CYCLO3',NULL,'Cyclodictyon Mitt.','cyclodictyon moss','Callicostaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25118','CYRIL',NULL,'Cyrilla Garden ex L.','titi','Cyrillaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25344','CYWA4',NULL,'Cyrtandra waiolani Wawra','fuzzyflower cyrtandra','Gesneriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25348','CYRTO5',NULL,'Cyrto-hypnum (Hampe) Hampe & Lor.','cyrto-hypnum moss','Thuidiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25365','CYRTO3',NULL,'Cyrtomnium Holmen','cyrtomnium moss','Mniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25376','CYRTO4',NULL,'Cyrtosperma Griffith','cyrtosperma','Araceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25432','DACRY2',NULL,'Dacrycarpus (Endl.) Laubenf.','dacrycarpus','Podocarpaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25493','DACTY5',NULL,'Dactylospora K&#8730;&#8706;rb.','dactylospora lichen','Dactylosporaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25720','DALTO',NULL,'Daltonia Hook. & Taylor','daltonia moss','Daltoniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25727','DANAE',NULL,'Danaea Sm.','danafern','Marattiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25776','DARLI',NULL,'Darlingtonia Torr.','California pitcherplant','Sarraceniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25815','DATIS',NULL,'Datisca L.','datisca','Datiscaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25856','DEEU',NULL,'Dedeckera eurekensis Reveal & J.T. Howell','July gold','Polygonaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25859','DEERI',NULL,'Deeringothamnus Small','false pawpaw','Annonaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('25864','DEGEL',NULL,'Degelia Arv. & D.J. Galloway','degelia lichen','Pannariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('26112','DERE2',NULL,'Delphinium recurvatum Greene','Byron larkspur','Ranunculaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('26147','DENDR9',NULL,'Dendriscocaulon Nyl.','dendriscocaulon lichen','Lobariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('26153','DENDR8',NULL,'Dendroalsia E. Britton','dendroalsia moss','Leucodontaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('26170','DENDR10',NULL,'Dendrographa Darbish.','dendrographa lichen','Roccellaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('26185','DENDR2',NULL,'Dendropanax Decne. & Planch.','dendropanax','Araliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('26188','DENDR3',NULL,'Dendropemon (Blume) Schult. & Schult. f.','leechbush','Loranthaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('26206','DENNS',NULL,'Dennstaedtia Bernh.','hayscented fern','Dennstaedtiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('26753','DIAPE',NULL,'Diapensia L.','diapensia','Diapensiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('27239','DICHE3',NULL,'Dichelyma Myr.','dichelyma moss','Fontinalaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('27271','DICKS',NULL,'Dicksonia L''H&#8730;©r.','tree fern','Dicksoniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('27429','DICTY',NULL,'Dictyonema C. Agardh','dictyonema lichen','Corticiaceae')
GO
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('27704','DILLE2',NULL,'Dillenia L.','dillenia','Dilleniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('27715','DIMEL',NULL,'Dimelaena Norman','mountain lichen','Physciaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('27799','DIOSC',NULL,'Dioscorea L.','yam','Dioscoreaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('27841','DIOSP',NULL,'Diospyros L.','diospyros','Ebenaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('27998','DIPLO2',NULL,'Diplopterygium (Diels) Nakai','diplopterygium','Gleicheniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('28001','DIPLO5',NULL,'Diploschistes Norman','crater lichen','Thelotremataceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('28085','DISCE',NULL,'Discelium Brid.','discelium moss','Disceliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('28350','DOODI',NULL,'Doodia R. Br.','hacksaw fern','Blechnaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('28721','DRACA',NULL,'Dracaena L.','dracaena','Agavaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('28771','DRIMY',NULL,'Drimys J.R. Forst. & G. Forst.','drimys','Winteraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('28779','DROSE',NULL,'Drosera L.','sundew','Droseraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('28928','DRSA',NULL,'Dryopteris sandwicensis (Hook. & Arn.) C. Chr.','Pacific woodfern','Dryopteridaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29185','DUST',NULL,'Dudleya stolonifera Moran','Laguna Beach liveforever','Crassulaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29226','DURIO',NULL,'Durio Adanson','durio','Bombacaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29228','DYCKI',NULL,'Dyckia Schult. f.','dyckia','Bromeliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29285','ECCRE',NULL,'Eccremidium Wilson','eccremidium moss','Ditrichaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29442','ECREB2',NULL,'Echinocereus reichenbachii (Terscheck ex Walp.) hort ex Haage ssp. baileyi (Rose) N.P. Taylor','Bailey''s hedgehog cactus','Cactaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29631','ECHIN10',NULL,'Echinothecium Zopf','echinothecium lichen','Capnodiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29697','EIPA',NULL,'Eichhornia paniculata (Spreng.) Solms','Brazilian water hyacinth','Pontederiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29699','EIGLE',NULL,'Eiglera Hafellner','eiglera lichen','Eigleraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29703','ELAEA',NULL,'Elaeagnus L.','oleaster','Elaeagnaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29718','ELAEO',NULL,'Elaeocarpus L.','elaeocarpus','Elaeocarpaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('29771','ELATI',NULL,'Elatine L.','waterwort','Elatinaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30539','EMBOT',NULL,'Embothrium J.R. Forst. & G. Forst.','Chilean firebush','Proteaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30561','EMPET',NULL,'Empetrum L.','crowberry','Empetraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30725','ENSET',NULL,'Ensete Horan.','ensete','Musaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30742','ENTER4',NULL,'Enterographa F&#8730;©e','enterographa lichen','Opegraphaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30765','ENTER3',NULL,'Enterosora Baker','threefork polypody','Grammitidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30769','ENTOD2',NULL,'Entodon M&#8730;ºll. Hal.','entodon moss','Entodontaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30789','ENTOD3',NULL,'Entodontopsis Broth.','entodontopsis moss','Stereophyllaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30796','ENTOS',NULL,'Entosthodon Schw&#8730;§gr.','entosthodon moss','Funariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30817','EOPYR',NULL,'Eopyrenula R.C. Harris','eopyrenula lichen','Pleomassariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30831','EPHED',NULL,'Ephedra L.','jointfir','Ephedraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30863','EPHEM',NULL,'Ephemerum Hampe','ephemerum moss','Ephemeraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('30977','EPCA3',NULL,'Epilobium canum (Greene) P.H. Raven','hummingbird trumpet','Onagraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('31159','EQUIS',NULL,'Equisetum L.','horsetail','Equisetaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('31488','ERSPS2',NULL,'Eriastrum sparsiflorum (Eastw.) H. Mason ssp. sparsiflorum','Great Basin woollystar','Polemoniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('32256','ERCA7',NULL,'Eriodictyon capitatum Eastw.','Lompoc yerba santa','Hydrophyllaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('33218','ERPOD',NULL,'Erpodium (Brid.) Brid.','erpodium moss','Erpodiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('33280','ERPH3',NULL,'Eryngium phyteumae Delar. f.','Huachuca Mountain eryngo','Apiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('33469','ERYTH5',NULL,'Erythroxylum P. Br.','coca','Erythroxylaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('33794','EUGR16',NULL,'Eucalyptus grossa F. Muell. ex Benth.','coarse-leaf mallee','Myrtaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('34049','EUCNI',NULL,'Eucnide Zucc.','stingbush','Loasaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('34056','EUCRY2',NULL,'Eucryphia Cav.','ulmo','Cunoniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('34649','EURYA',NULL,'Eurya Thunb.','eurya','Theaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('34654','EURYA2',NULL,'Euryale Salisb.','euryale','Nymphaeaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35057','FAYOD',NULL,'Fayodia Kuhner','fayodia lichen','Tricholomataceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35073','FEBO',NULL,'Fellhanera bouteillei (Desmaz.) Vezda','Bouteille''s fellhanera lichen','Pilocarpaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35078','FENDL',NULL,'Fendlera Engelm. & A. Gray','fendlerbush','Hydrangeaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35361','FIBRA',NULL,'Fibraurea Lour.','fibraurea','Menispermaceae')
GO
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35363','FICUS',NULL,'Ficus L.','fig','Moraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35507','FISSI2',NULL,'Fissidens Hedw.','fissidens moss','Fissidentaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35585','FICU2',NULL,'Fitzroya cupressoides (Molina) I.M. Johnst.','Patagonian cypress','Cupressaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35586','FLACO',NULL,'Flacourtia Comm. ex L''H&#8730;©r.','flacourtia','Flacourtiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35818','FOUQU',NULL,'Fouquieria Kunth','ocotillo','Fouquieriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('35933','FRANK',NULL,'Frankenia L.','seaheath','Frankeniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('36112','FREYC',NULL,'Freycinetia Gaudich.','freycinetia','Pandanaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('36352','FUKO',NULL,'Fuscidea kochiana (Hepp) V. Wirth & Vezda','fuscidea lichen','Fuscideaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('36865','GATRT5',NULL,'Galium trifidum L. ssp. trifidum','threepetal bedstraw','Rubiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('36971','GARRY',NULL,'Garrya Douglas ex Lindl.','silktassel','Garryaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('37120','GEGI',NULL,'Geheebia gigantea (Funck) Boul.','giant geheebia moss','Pottiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('37122','GELSE',NULL,'Gelsemium Juss.','trumpetflower','Loganiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('37379','GEVIV2',NULL,'Gentianopsis virgata (Raf.) Holub ssp. victorinii (Fernald) Lammers','Victorin‚Äôs gentian','Gentianaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('37393','GEOCA',NULL,'Geocaulon Fernald','false toadflax','Santalaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('37412','GERAN',NULL,'Geranium L.','geranium','Geraniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('37755','GINKG',NULL,'Ginkgo L.','ginkgo','Ginkgoaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('37759','GISEK',NULL,'Gisekia L.','gisekia','Phytolaccaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('37929','GLINU',NULL,'Glinus L.','sweetjuice','Molluginaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('37948','GLOSS',NULL,'Glossopetalon A. Gray','greasebush','Crossosomataceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('38074','GNETU',NULL,'Gnetum L.','jointfir','Gnetaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('38375','GREYI',NULL,'Greyia Hook. & Harv.','Natal bottlebrush','Greyiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('38401','GRMO5',NULL,'Grimmia montana Bruch & Schimp.','montane dry rock moss','Grimmiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('38656','GUNNE',NULL,'Gunnera L.','gunnera','Gunneraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('38719','GYALE2',NULL,'Gyalecta Ach.','dimple lichen','Gyalectaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('38733','GYALI',NULL,'Gyalidea Lettau ex Vezda','gyalidea lichen','Solorinellaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('38864','GYPSO2',NULL,'Gypsoplaca Timdal','gypsoplaca lichen','Gypsoplaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('38965','HAEMA3',NULL,'Haematomma A. Massal.','bloodstain lichen','Haematommataceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('38979','HAENI',NULL,'Haenianthus Griseb.','haenianthus','Oleaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39007','HALEC',NULL,'Halecania M. Mayrh.','halecania lichen','Catillariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39017','HALES',NULL,'Halesia Ellis ex L.','silverbell','Styracaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39052','HALOD',NULL,'Halodule Endl.','halodule','Cymodoceaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39071','HALOR',NULL,'Haloragis J.R. Forst. & G. Forst.','seaberry','Haloragaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39261','HECIS',NULL,'Hecistopteris J. Sm.','hecistopteris','Vittariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39321','HEDWI',NULL,'Hedwigia P. Beauv.','hedwigia moss','Hedwigiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39330','HEDYO',NULL,'Hedyosmum Sw.','hedyosmum','Chloranthaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39797','HELIC2',NULL,'Heliconia L.','heliconia','Heliconiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39936','HELLE2',NULL,'Helleriella A.D. Hawkes','helleriella','Orchidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39938','HELMI',NULL,'Helminthocarpon F&#8730;©e','helminthocarpon lichen','Graphidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39940','HELMI2',NULL,'Helminthostachys Kaulf.','helminthostachys','Ophioglossaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39942','HELOC2',NULL,'Helocarpon Th. Fr.','helocarpon lichen','Micareaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39946','HELOD',NULL,'Helodium Warnst.','helodium moss','Helodiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('39983','HEMIT',NULL,'Hemitomes A. Gray','coneplant','Monotropaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('40023','HENIC2',NULL,'Henicodium (M&#8730;ºll. Hal.) Kindb.','henicodium moss','Pterobryaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('40055','HEPPI',NULL,'Heppia Nageli','heppia lichen','Heppiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('40106','HERNA',NULL,'Hernandia L.','hernandia','Hernandiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('40192','HEAD',NULL,'Hesperolinon adenophyllum (A. Gray) Small','glandular dwarf-flax','Linaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('40704','HIBIS',NULL,'Hibiscadelphus Rock','hibiscadelphus','Malvaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('40996','HILLE',NULL,'Hillebrandia Oliv.','hillebrandia','Begoniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41014','HIPPO2',NULL,'Hippocratea L.','hippocratea','Hippocrateaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41033','HIPPU',NULL,'Hippuris L.','mare''s-tail','Hippuridaceae')
GO
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41166','HOMAL3',NULL,'Homalia (Brid.) Schimp.','homalia moss','Neckeraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41216','HOAD',NULL,'Homomallium adnatum (Hedw.) Broth.','homomallium moss','Hypnaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41244','HOOKE',NULL,'Hookeria Sm.','hookeria moss','Hookeriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41247','HOPEA',NULL,'Hopea Roxb.','hopea','Dipterocarpaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41498','HOUTT',NULL,'Houttuynia Thunb.','houttuynia','Saururaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41555','HUMUL',NULL,'Humulus L.','hop','Cannabaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41716','HYBAN',NULL,'Hybanthus Jacq.','greenviolet','Violaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('41812','HYDRO9',NULL,'Hydrothyria J.L. Russell','hydrothyria lichen','Peltigeraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('42063','HYMEN5',NULL,'Hymenophyllum Sm.','filmy fern','Hymenophyllaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('42486','HYPOP3',NULL,'Hypopterygium Brid.','hypopterygium moss','Hypopterygiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('42595','ICACI',NULL,'Icacina A. Juss.','icacina','Icacinaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('42608','ICMAD',NULL,'Icmadophila Trevis.','peppermint drop lichen','Baeomycetaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('42612','ILEX',NULL,'Ilex L.','holly','Aquifoliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('42709','ILLIC',NULL,'Illicium L.','anisetree','Illiciaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('42718','IMPAT',NULL,'Impatiens L.','touch-me-not','Balsaminaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('42754','INCAR',NULL,'Incarvillea Juss.','incarvillea','Bignoniaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('43525','ISOET',NULL,'Isoetes L.','quillwort','Isoetaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('43713','ITEA',NULL,'Itea L.','sweetspire','Grossulariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('43806','IWATS',NULL,'Iwatsukiella W.R. Buck & H.A. Crum','iwatsukiella moss','Pterigynandraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('43867','JACQU2',NULL,'Jacquinia L.','jacquinia','Theophrastaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('43926','JARIL',NULL,'Jarilla Rusby','jarilla','Caricaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44010','JOINV',NULL,'Joinvillea Gaudich. ex Brongn. & Gris','joinvillea','Joinvilleaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44032','JUJA',NULL,'Juglans jamaicensis C. DC.','West Indian walnut','Juglandaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44049','JULEL2',NULL,'Julella J.H.C. Fabre','julella lichen','Thelenellaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44288','JUPHP',NULL,'Juncus phaeocephalus Engelm. var. paniculatus Engelm.','brownhead rush','Juncaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44544','JUOVO',NULL,'Justicia ovata (Walter) Lindau var. ovata','looseflower water-willow','Acanthaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44565','KAEMP2',NULL,'Kaempferia L.','kaempferia','Zingiberaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44740','KIRSC',NULL,'Kirschsteiniothelia D. Hawksw.','kirschsteiniothelia lichen','Pleosporaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44811','KOELR',NULL,'Koelreuteria Laxm.','koelreuteria','Sapindaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44822','KOERB',NULL,'Koerberia A. Massal.','koerberia lichen','Placynthiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44830','KOHLM',NULL,'Kohlmeyera Schatz','kohlmeyera lichen','Mastodiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('44861','KRAME',NULL,'Krameria L.','ratany','Krameriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('45065','LACHN2',NULL,'Lachnanthes Elliot','lachnanthes','Haemodoraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('45071','LACHN',NULL,'Lachnocaulon Kunth','bogbutton','Eriocaulaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('45176','LAGET',NULL,'Lagetta Juss.','lagetta','Thymelaeaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('45314','LAIN4',NULL,'Laportea interrupta (L.) Chew','Hawai''i woodnettle','Urticaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('45370','LASAL2',NULL,'Lasallia M&#8730;©rat','blistered navel lichen','Umbilicariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('45824','LEAP3',NULL,'Lecanora applegatei Herre','Applegate''s rim lichen','Lecanoraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46081','LEMAV',NULL,'Lechea maritima Leggett ex Britton, Sterns & Poggenb. var. virginica Hodgdon','Virginia pinweed','Cistaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46109','LECID2',NULL,'Lecidea Ach.','lecidea lichen','Lecideaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46331','LECID4',NULL,'Lecidoma Gotth. Schneid. & Hertel','lecidoma lichen','Psoraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46339','LECYT',NULL,'Lecythis Loefl.','lecythis','Lecythidaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46396','LEITN',NULL,'Leitneria Chapm.','corkwood','Leitneriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46446','LEMNA',NULL,'Lemna L.','duckweed','Lemnaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46546','LEPIA',NULL,'Lepianthes Raf.','lepianthes','Piperaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46710','LEPIS',NULL,'Lepisorus (J. Sm.) Ching','lepisorus','Polypodiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46855','LERI6',NULL,'Leptodictyum riparium (Hedw.) Warnst.','streamside leptodictyum moss','Amblystegiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('46879','LEPTO17',NULL,'Leptodon D. Mohr','leptodon moss','Leptodontaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('47150','LESCU',NULL,'Lescuraea Schimp.','lescuraea moss','Leskeaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('47465','LETHA2',NULL,'Lethariicola Grummann','lethariicola lichen','Odontotremataceae')
GO
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('47468','LETRO',NULL,'Letrouitia Hafellner & Bellem.','letrouitia lichen','Letrouitiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('47515','LEUCO9',NULL,'Leucobryum Hampe','leucobryum moss','Leucobryaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('47561','LEPA39',NULL,'Leucopogon parviflorus (Andrews) Lindl.','coast beard-heath','Epacridaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('47618','LEOP',NULL,'Lewisia oppositifolia (S. Watson) B.L. Rob.','oppositeleaf lewisia','Portulacaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('47890','LICAN',NULL,'Licania Aubl.','licania','Chrysobalanaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('47908','LICHE',NULL,'Lichenochora Hafellner','lichenochora lichen','Phyllachoraceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('47924','LICHE4',NULL,'Lichenostigma Hafellner','lichenostigma lichen','Lichenotheliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('48004','LILAE',NULL,'Lilaea Bonpl.','lilaea','Juncaginaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('48129','LIFL2',NULL,'Limnanthes floccosa Howell','woolly meadowfoam','Limnanthaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('48139','LIMNO',NULL,'Limnobium Rich.','spongeplant','Hydrocharitaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('48149','LIMNO5',NULL,'Limnocharis Humb. & Bonpl.','velvetleaf','Limnocharitaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('48168','LIMON',NULL,'Limonium Mill.','sea lavender','Plumbaginaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('48654','LIRIO',NULL,'Liriodendron L.','tuliptree','Magnoliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('48703','LITHO5',NULL,'Lithographa Nyl.','lithographa lichen','Rimulariaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('48788','LITTO',NULL,'Littorella P.J. Bergius','littorella','Plantaginaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('49001','LOESK2',NULL,'Loeskeobryum Fleisch.','loeskeobryum moss','Hylocomiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('49409','LOVI',NULL,'Lonicera villosa (Michx.) Schult.','mountain fly honeysuckle','Caprifoliaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('49412','LOPAD',NULL,'Lopadium K&#8730;&#8706;rb.','granular lichen','Ectolechiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('49447','LOPHO3',NULL,'Lophosoria C. Presl','lophosoria','Lophosoriaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('49532','LOREN',NULL,'Lorentziella M&#8730;ºll. Hal.','lorentziella moss','Gigaspermaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('51041','LYCOP6',NULL,'Lycopodiella Holub','clubmoss','Lycopodiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('51200','LYVI4',NULL,'Lycopus virginicus L.','Virginia water horehound','Lamiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('51208','LYELL',NULL,'Lyellia R. Br.','lyellia moss','Polytrichaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('51230','LYGOD2',NULL,'Lygodium Sw.','climbing fern','Lygodiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('51719','MACRO7',NULL,'Macromitrium Brid.','macromitrium moss','Orthotrichaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('51746','MACRO3',NULL,'Macrothelypteris (H. It&#8730;¥) Ching','macrothelypteris','Thelypteridaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('51762','MACRO8',NULL,'Macrozamia Miq.','macrozamia','Zamiaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('52482','MASI2',NULL,'Marcgravia sintenisii Urb.','shingleplant','Marcgraviaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('52549','MARSI',NULL,'Marsilea L.','waterclover','Marsileaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('52736','MAFL8',NULL,'Mauritia flexuosa L. f.','muriti','Arecaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('52752','MAYAC',NULL,'Mayaca Aubl.','mayaca','Mayacaceae')
INSERT INTO [plant] ([PlantID],[Symbol],[SynonymSymbol],[ScientificNameWithAuthor],[CommonName],[Family])
 VALUES ('52755','MAYTE',NULL,'Maytenus Molina','mayten','Celastraceae')
SET IDENTITY_INSERT [plant] OFF
 
 
CREATE TABLE [shipment] (
[ShipmentID] [int] IDENTITY (1,1) NOT NULL,
[Name] [varchar] (200) NOT NULL,
[CreateDate] [datetime] NOT NULL,
[UpdateDate] [datetime],
[Active] [tinyint] NOT NULL,
[Status] [varchar] (50),
PRIMARY KEY([ShipmentID])
)
GO

SET IDENTITY_INSERT [shipment] ON
INSERT INTO [shipment] ([ShipmentID],[Name],[CreateDate],[UpdateDate],[Active])
 VALUES ('1','Initial Shipments','10/8/2009 5:03:40 PM','10/10/2009 12:00:00 AM','1')
 SET IDENTITY_INSERT [shipment] OFF

 
 -- ----------------------------
-- Table structure for workflow
-- ----------------------------

 CREATE TABLE [workflow] (
 [WorkflowID] [int] IDENTITY (1,1) NOT NULL,
 [ShipmentID] [int] NOT NULL,
 [Workflow] [varchar] (300) NOT NULL,
 [CreateDate] [datetime] default(getdate())  NOT NULL,
 PRIMARY KEY([WorkflowID])
 )
 
